Protocol refactor
tlsnotary/docs-mdbook pull request #34
Opened 2023-09-06 19:45 UTC by sinui0

This PR refactors our "Protocol" section to sync with our newer communication strategy. The section is not complete but this is a start.

I moved the "Commitment" and "Signing" sections into 1 section under "Notarization".

2023-09-07 12:56 UTC, heeckhau requested changes
I think I am reviewing this in the wrong order. I'll review the introduction first, and next see how this PR fits in the flow.

2023-09-07 12:56 UTC, heeckhau commented on src/png-diagrams/mpc-decryption.png
the `drawio` file is missing for the `mpc-decryption`

2023-09-07 12:56 UTC, heeckhau commented on src/protocol/notarization.md
> +As part of the TLSNotary protocol, the `Prover` can create authenticated commitments to the plaintext and have the `Notary` sign them without ever seeing the plaintext. This offers a way for the `Pro
We will have to introduce the notary here again, as a special case where.

I may also be better to move this chapter to the end of the protocol chapters.

2023-09-12 09:04 UTC, themighty1 approved these changes

2023-09-14 10:20 UTC, themighty1 approved these changes
lgtm, sry github's "suggest a  change" didnt work for some reason

2023-09-14 10:20 UTC, themighty1 commented on src/diagrams/key_exchange.svg
requester is still present in the new diagram

2023-09-14 10:20 UTC, themighty1 commented on src/glossary.md
> +| 2PC   | Two-party computation                           |
Secure two-party computation

2023-09-14 10:20 UTC, themighty1 commented on src/glossary.md
> +| MPC   | Multi-party computation                         |
secure multi-party computation

2023-09-14 10:20 UTC, themighty1 commented on src/protocol/mpc-tls/README.md
> +The MPC-TLS consists of following steps:
the following steps

2023-09-14 10:20 UTC, themighty1 commented on src/protocol/mpc-tls/README.md
> +A TLS handshake is the first step in establishing a TLS connection between the `Prover`/`Verifier` and the `Server`. The result of this handshake is a *Pre Master Secret (PMS)*, a symmetrical key tha
"key that will be used for encrypt further communication"

2023-09-14 10:22 UTC, themighty1 commented on src/protocol/mpc-tls/README.md
> +A TLS handshake is the first step in establishing a TLS connection between the `Prover`/`Verifier` and the `Server`. The result of this handshake is a *Pre Master Secret (PMS)*, a symmetrical key tha
sry. misread the original text, ignore this comment.

2023-09-14 13:22 UTC, heeckhau approved these changes

2023-09-14 14:56 UTC, heeckhau commented on src/protocol/mpc-tls/README.md
> +for the data that ensures untampered communication.
OK. I wanted to give a short summary of what is coming next here.
I'll put it in comments for now.

2023-09-14 15:18 UTC, merged